### ISSUE TITLE
Latex input for labels, ticks and strings

### ISSUE THREAD

**Issue by lnacquaroli** [tlienart/GPlot.jl#157]
Hi there,

I just found the package. Great idea for LaTeX fans.

I was trying to copy the example in the docs:

```julia
preamble = texpreamble = tex"""
    \usepackage[utf8]{inputenc}
    \usepackage[sfdefault, scaled=0.85, lf]{FiraSans}
    \usepackage[T1]{fontenc}
    \usepackage{amsmath,amsthm,amssymb}
    \usepackage[cmintegrals,slantedGreek]{newtxsf}
    \usepackage{siunitx}
"""
fig = Figure(texpreamble=preamble)
x = range(-2.5, stop=2.5, length=100)
y = @. exp(-x^2) * sin(x)
plot(x, y, label="plot 1")
y2 = @. sin(x^2) * exp(-x/10)
plot!(x, y2, col="blue", lwidth=0.05, label="plot 2")
xlabel("x-axis")
ylabel("y-axis")
xticks([-pi/2, 0, pi/2], ["pi/2", "0", "pi/2"])
ylim(-1.5, 1.5)
yticks(-1:0.25:1)
legend()
```

But could not find a way to pass a LaTeX string into the `xticks`. Tried `"$\pi/2$"`, `"$\\pi/2$"`, and even with `LaTeXStrings` package unsuccessfully.

Is there a work around to it?

Thanks.

**Comment by lnacquaroli** [comment]
Maybe I am too biased from LaTeXStrings.jl, PyPlot.jl and Plots.jl. Escaping all the latex commands did the trick, and also (here is where my naive skills show their best), just using `tex"""$\pi/2$"""`.

```julia
preamble = texpreamble = tex"""
    \usepackage[utf8]{inputenc}
    \usepackage[sfdefault, scaled=0.85, lf]{FiraSans}
    \usepackage[T1]{fontenc}
    \usepackage{amsmath,amsthm,amssymb}
    \usepackage[cmintegrals,slantedGreek]{newtxsf}
    \usepackage{siunitx}
"""
fig = Figure(texpreamble=preamble)
x = range(-2.5, stop=2.5, length=100)
y = @. exp(-x^2) * sin(x)
plot(x, y, label="plot 1")
y2 = @. sin(x^2) * exp(-x/10)
plot!(x, y2, col="blue", lwidth=0.05, label="plot 2")
xlabel("x-axis")
ylabel("y-axis")
xticks([-pi/2, 0, pi/2], ["-\$\\pi/2\$", "0", tex"""$\pi/2$"""])
ylim(-1.5, 1.5)
yticks(-1:0.25:1)
legend()
```

So, it looks (at least for me) that the `tex""" """` replaces `L" "` from LaTeXStrings.jl.

**Comment by tlienart** [comment]
Oh yes, this should be in the docs (sorry as mentioned in the other isssue I haven't had much time to push this project recently) but basically `tex"..."` is the  way to go, it's simpler and faster than LaTeXStrings because it's simpler (GPlot doesn't need the fanciness)

And you don't need triple quotes so for instance this works:

```
xtitle!(tex"The $x$ axis $\int_0^\infty f(x)\mathrm{d}x$", color="blue",
            fontsize=12)
```

**Comment by tlienart** [comment]
Oh and other trick, I had also allowed for the shorter `t"..."` it saves two characters which is a whopping 66% improvement. (but if you have to use for xticks for instance it might be useful 😋 )

**Comment by tlienart** [comment]
Final comment, feel free to open issues, I'll do my best to help you out, for all basic plots GPlot should basically be ready to go, for more sophisticated stuff well... there's a few things that are available but not yet documented (I really need to just finish the docs and release the damn thing)

Oh and could you tell me whether you're using Mac, Linux or Windows and whether it was painful to install  GLE etc? would be very useful to improve the docs, thanks!

**Comment by lnacquaroli** [comment]
Great, thanks for all the comments.

Was wondering actually if there was a shorter for `tex""" """`, so `t" "` does it perfectly, thanks.

Notice that, with latex styling, if I insert directly the `\pi[TAB]`, without rendering it as a latex string it won't work. It wouldn't render the texts in the plot, just the lines. So I have to stick to the `t" "` thing. I tried with two different fonts in the preamble for this. If you are not using latex styling this works though, as described in the docs.

For the more sophisticated stuff, I would say that the are two missing things (for me) that are useful sometimes: the contour plot capability, and the annotations. I don't know if these are existing functionalities already or just missing in the docs (or maybe I just missed them in the docs).

As regards the GLE, fortunately, I'm using Linux (Ubuntu) so the installation was as easy as described in the docs, `sudo apt install gle-graphics` and that's it, it worked without any issues.

Thanks for your help.

**Comment by tlienart** [comment]
Fantastic, 

And yes you're right, use the symbol without latex styling or use latex styling and the latex command, you can't mix both. Looks like you worked that out fine.

Countours are not done yet but it's the last thing I was working on (3D stuff), so there's already some basic support and GLE supports contours quite well so it's not hard to add that.

Annotations are there, see `?text`, `?hline` and `?vline`

```
text("blah", (0,0))
```

Does what you think; you can also add `hline` and `vline` to point to specific places; no arrows (yet) though.

**Comment by lnacquaroli** [comment]
> Annotations are there, see ?text, ?hline and ?vline

Missed that out. They work.

All right, I will close this now to not take the issue of the tracks from what the title says. If I get into any other issue I'll come back.

Thanks!

**Comment by tlienart** [comment]
By the way, having someone who (even casually) uses the package is a great motivator so while I definitely  understand you may only use it from time to time because it's not feature complete etc, all feedback / missing things / whatever comes to mind / nice plots that you've managed to  do, everything would be welcome, I should be able to react reasonably quickly 😄
