### ISSUE TITLE
I got BLAHBLAHBLAH in Atom editor

### ISSUE THREAD

**Issue by lnacquaroli** [tlienart/GPlot.jl#158]
I don't know where this comes from. Check the red circle in the REPL.

![weird_msg](https://user-images.githubusercontent.com/26485264/66010429-d44ed000-e48c-11e9-968c-63201e4ff69d.png)

This happens after executing the examples. Any ideas?

**Comment by tlienart** [comment]
Oh my...

Haha, so yes this is a leftover of some debugging I was doing with the show method... sorry about that will fix soon.

Btw, hello! I've not really managed to push this package past an acceptable "release" state over the last few months as I was busy with a bunch of other projects but it's very much my intention to get back to it. Feedback is much appreciated, thanks!
